### PR TITLE
Add Dockerfile to easily publish a Docker container

### PR DESCRIPTION
**Pull request by 0xThiebaut**
By adding this Dockerfile, one can easily build a container by using `docker build` and publish it afterwards on the [Docker Hub](https://hub.docker.com).
```
docker build . -t bricaud/graphexp 
```
This is needed as the [joov/gremlin-demo](https://github.com/joov/gremlin-demo) repository mentioned in the documentation still does not offer a published container and is uselessly complicated.

As an example, I published the [0xthiebaut/graphexp](https://hub.docker.com/r/0xthiebaut/graphexp) container allowing this repository to be ran using `docker run`.
```
docker run --rm -dit -p 8080:80 0xthiebaut/graphexp
```

There are currently just under 20 versions of graphexp on Docker, a version owned and maintained by the author @bricaud would be appreciated.

### CODE REVIEW

**Comment by 0xThiebaut** [comment]
Seems this feature is also requested in #37 .

**Comment by bricaud** [comment]
Thanks @0xThiebaut ! I just merged your pr. That would be great if you can modify the readme file to explain how to use it, as you did in the comment, with a link to your example and any other links you think useful. I am on holidays right now.

**Comment by 0xThiebaut** [comment]
I'd happily do so.

Can I assume that somewhere in the near future you'll publish the container on Docker Hub under your account? This would allow for an authoritative `bricaud/graphexp` container matching this repository's location. If so, does your Docker username match the GitHub one?

Enjoy your holidays! 🌴

**Comment by bricaud** [comment]
Thanks. Good idea for the docker hub repo, yes I have an account with login bricaud. Put the link to yours in the readme and I will add mine when I am back.

**Pull request merged**
