### PR TITLE
Relative dependency URLs

### PR DESCRIPTION
**Pull request by joebernard**
I've updated graphexp.html to use relative URLs for the d3 and jquery dependencies. This was causing a problem when loading the app with https.

### CODE REVIEW

**Comment by bricaud** [comment]
Thanks for pointing out this issue. Why not changing `http` to `https` in the URL of d3 and jquery instead?

**Comment by joebernard** [comment]
You could do that too, but then it would force `http` users to download those libraries over `https` unnecessarily. I like using relative urls like this so the libs are only encrypted if the entire request needs to be encrypted. Best of both worlds.

**Comment by joebernard** [comment]
Bear in mind that this is an incomplete fix, since it looks like the rest and ws calls will need to be relative as well. If I have time I'll submit another PR for those issues.

**Comment by jwalton922** [comment]
I've been looking at this as well. I think it breaks if it's being viewed
as file:// as the directions stated (at least used to). I personally think
the project should be hosted. The github page branch just needs to be
updated. It will also need the appropriate protocol for the rest and WS
calls.

**Comment by bricaud** [comment]
with the `file://` version, I would need to copy the jquery and d3.js files into the graphexp repo. I want to keep a clear separation between the graphexp files and the external libraries, so I will keep it as it is. But I will add a comment in the readme about installing the d3 and jquery files in the graphexp path to get a easier loading in particular when using https.
If you make this PR with modification on ws and rest requests, I will include it and add an option in the conf file to use the original one or the https adapted version.

**Pull request closed without merging**
