### PR TITLE
Fix child traversal error in query

### PR DESCRIPTION
**Pull request by dboreham**

### CODE REVIEW

**Comment by slastrina** [comment]
This fixed works great, thanks @dboreham

**Comment by slastrina** [comment]
@bricaud, it doesnt look like much traction in this repo anymore sadly, but this fix is worth bringing into master. on 0.62 janugraph this change fixed traversals after the first node.

**Comment by bricaud** [comment]
ok, then I will take some time this week to check and include it in the master. Thanks

**Comment by slastrina** [comment]
> ok, then I will take some time this week to check and include it in the master. Thanks

Cheers mate, i think theres still one issue remaining, looks like on 0.62 with gremlin 3.4 the vertex properties don't populate, edges are working fine though

**Pull request merged**
