### PR TITLE
adding bootstrap style v1

### PR DESCRIPTION
**Pull request by armandleopold**
This is a draft for making the UI more friendly for casual users. 
Using Bootstrap V4 framework

### CODE REVIEW

**Comment by bricaud** [comment]
Thanks @erandal . There are a lot of changes! I think I will first make a new branch with the changes and see what we can do with it. I don't know if I will use this contribution to modify the master or if we separate it as a different version of Graphexp, in a different branch.

**Comment by erandal** [comment]
Alright ;) no problemo. As you can see there is no modification to the JS. Only style.

**Comment by bricaud** [comment]
The interface is really nice!
However I am hesitating to merge it:
* I am not sure I can maintain it if you are too busy to do it in the future
* It may prevent people adding new functionalities, for example @sandecho has added the possibility to add nodes and vertices in PR #38 
* There are plenty of new files, which are in fact coming from bootstrap, with an MIT licence. This will make the program a bit messy.
What I am thinking about now is either 
* to make a new 'boostrap version' branch on my repo. I would add a link to it in the readme for those interested
* add a link to your repo in the readme, then people can use your version if they want (and star it if they like it). And you would regularly update your fork when there are new modifications in the code.
Do you have any other suggestions or preferences?

**Comment by erandal** [comment]
The second option seems the better one from my point of view. 
I can update the interface User interface with the Bootstrap theme on my repo,  and you can still have a licence free soft with only maintaining functionnalities.

Sounds ok to me.
I was planning to continue to work on it this week-end.

**Comment by bricaud** [comment]
Ok, let us do this! We can always change in the future if we find a better solution.
So I will merge PR #38 this week end and do some modifications on the code. I can not merge it right now because I did not test it completely. Then you tell me when you branch is ready and I put a link to it on my readme, with a description.

**Comment by erandal** [comment]
It's done for me !

**Comment by bricaud** [comment]
ok, I have put a link in my readme file to point to your repo. Then people can try it and give us some feedback. Let us see what they say!
You did not add the 'edit graph' function on your version?

**Comment by bricaud** [comment]
Thanks a lot for your work.
Would you be interested in the future if I create an organization account and I put graphexp there? Then you can manage the project with me (and hopefully others) and we can merge your bootstrap contribution.

**Comment by erandal** [comment]
I was working on it. This is good now. 
Yes if you want ! 
Actually i had the need of a fast graph explorer with interactivity not like on a jupyter notebook.
I'm working on running some Machine learning graph algorithms.
Needed to have some insights on my results ;)
So as long as i am working on this topic, i would be glad to be a part of your project.
Sound's great.

**Review by bricaud — APPROVED** [review]
Make the UI a bit more heavy, but it is nice to have. Thanks

**Comment by armandleopold** [comment]
I have resolved conflicts, need to be checked anyway. If you want i made a Docker Image out of the sources at : https://hub.docker.com/r/aleopold/docker-graphexp

**Comment by bricaud** [comment]
I realize that I can't just merge the commit about custom support. I have to merge the whole branch with many other changes that were made before. It is a bit messy and difficult to track the changes. I prefer not to do it like this. Sorry.

**Comment by armandleopold** [comment]
As you wish =)

**Comment by armandleopold** [comment]
Hello i have resolved all the conflics. I have tagged my sources as v0.8.2.
You can merge without fear.

**Comment by armandleopold** [comment]
Added Dockerfile to build docker package within github repo.

**Comment by bricaud** [comment]
cleaning repo. Please submit a new pull request if you want some changes to be included.

**Pull request closed without merging**
